version: 2.1

executors:
  job-environment:
    shell: /bin/bash --login -eo pipefail
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      HOMEBREW_LOGS: ~/homebrew-logs
      HOMEBREW_TEMP: ~/homebrew-temp
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      FL_OUTPUT_DIR: output
      FASTLANE_EXPLICIT_OPEN_SIMULATOR: 2

commands:
  prepare:
    parameters:
      ruby:
        type: string
        default: "2.7.4p191"
      xcode:
        type: string
        default: "13.0.0"
    steps:
      - restore_cache:
          keys:
          - jwtdecode-swift-gems-{{ checksum "Gemfile.lock" }}
          - jwtdecode-swift-gems-
      - run:
          name: Install gems
          command: |
            echo "ruby-<< parameters.ruby >>" > ~/.ruby-version
            bundle check || bundle install --without=development
      - save_cache:
          key: jwtdecode-swift-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Install Carthage
          command: brew update && brew upgrade carthage
      - run:
          name: Install Swiftlint
          command: brew install swiftlint
      - run:
          name: Enable code coverage
          command: grep -lR "shouldUseLaunchSchemeArgsEnv" *.* --null | xargs -0 sed -i '' -e 's/shouldUseLaunchSchemeArgsEnv = "YES"/shouldUseLaunchSchemeArgsEnv = "YES" codeCoverageEnabled = "YES"/g'
      - restore_cache:
          keys:
            - jwtdecode-swift-carthage-{ checksum "Cartfile.resolved" }}-<< parameters.xcode >>
            - jwtdecode-swift-carthage-{ checksum "Cartfile.resolved" }}
            - jwtdecode-swift-carthage-
      - command: 
          name: Install dependencies
          command: carthage bootstrap --use-xcframeworks --no-use-binaries --cache-builds
      - save_cache:
          key: jwtdecode-swift-carthage-{ checksum "Cartfile.resolved" }}-<< parameters.xcode >>
          paths:
            - Carthage/Build
  test-ios:
    steps:
      - run: 
          name: Run iOS tests
          command: bundle exec fastlane ios ci
  pod-lint:
    steps:
      - run: 
          name: Run pod lib lint
          command: bundle exec fastlane ios pod_lint
  upload-coverage:
    steps:
      - run: 
          name: Upload coverage report
          command: bash <(curl -s https://codecov.io/bash) -J 'JWTDecode'
  test-macos:
    steps: 
      - run: 
          name: Run macOS tests
          command: |
            security create-keychain -p circle cikeychain
            security list-keychains -d user -s "/Users/distiller/Library/Keychains/xcode.keychain-db" /Users/distiller/Library/Keychains/cikeychain-db
            security default-keychain -s /Users/distiller/Library/Keychains/cikeychain-db
            security unlock-keychain -p circle "/Users/distiller/Library/Keychains/cikeychain-db"
            xcodebuild test -scheme JWTDecode-OSX -destination 'platform=macOS,arch=x86_64' | xcpretty
            swift test
  test-tvos:
    steps: 
      - run: 
          name: Run tvOS tests
          command: xcodebuild test -scheme JWTDecode-tvOS -destination 'platform=tvOS Simulator,name=Apple TV' | xcpretty

jobs:
  build-and-test-iOS-xcode-13:
    executor: job-environment
    steps:
      - checkout
      - prepare
      - test-ios
      - upload-coverage
      - pod-lint
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output
  build-and-test-macOS-xcode-13:
    executor: job-environment
    steps:
      - checkout
      - prepare
      - test-macos
  build-and-test-tvOS-xcode-13:
    executor: job-environment
    steps:
      - checkout
      - prepare
      - test-tvos
  build-and-test-iOS-xcode-12:
    executor: job-environment
    macos:
      xcode: "12.5.1"
      ruby: "2.7.4p191"
    steps:
      - checkout
      - prepare
      - test-ios
  build-and-test-macOS-xcode-12:
    executor: job-environment
    macos:
      xcode: "12.5.1"
      ruby: "2.7.4p191"
    steps:
      - checkout
      - prepare
      - test-macos
  build-and-test-tvOS-xcode-12:
    executor: job-environment
    macos:
      xcode: "12.5.1"
      ruby: "2.7.4p191"
    steps:
      - checkout
      - prepare
      - test-tvos

workflows:
  build:
    jobs:
      -  build-and-test-iOS-xcode-13
      -  build-and-test-macOS-xcode-13
      -  build-and-test-tvOS-xcode-13
      -  build-and-test-iOS-xcode-12
      -  build-and-test-macOS-xcode-12
      -  build-and-test-tvOS-xcode-12
